name: CI/CD for Customer Feedback Analyzer

on:
  push:
    branches:
      - main  # This workflow runs on pushes to the main branch

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: "us-east1" # Change this to your preferred GCP region
  ARTIFACT_REPO_NAME: feedback-analyzer-repo # Name of your Artifact Registry repo
  SERVICE_NAME: feedback-analyzer-api
  WORKER_NAME: feedback-analyzer-worker
  IMAGE_NAME: feedback-analyzer

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ github.run_attempt }} .
        docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ github.run_attempt }}

    - name: Deploy API Service to Cloud Run
      env:
        ENV_VARS: "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},REDIS_URI=${{ secrets.REDIS_URI }},DATABASE_URI=${{ secrets.DATABASE_URI }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }}"
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ github.run_attempt }} \
          --region ${{ env.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="$ENV_VARS" \
          --vpc-connector feedback-analyzer-connect

    - name: Deploy Worker Service to Cloud Run
      env:
        ENV_VARS: "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},REDIS_URI=${{ secrets.REDIS_URI }},DATABASE_URI=${{ secrets.DATABASE_URI }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }}"
      run: |
        gcloud run jobs deploy ${{ env.WORKER_NAME }} \
          --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ github.run_attempt }} \
          --region ${{ env.GCP_REGION }} \
          --set-env-vars="$ENV_VARS" \
          --vpc-connector feedback-analyzer-connect \
          --command="python" \
          --args="run_worker.py"